version: "3.8"
services:
    web:
        image: aleksovops/devops-aleksov-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/devopsapp/web:/var/www/html:ro"
        networks:
            - devops-network
    db:
        image: aleksovops/devops-aleksov-db
        networks:
            - devops-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    devops-network:

