version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/devopsapp/web:/var/www/html:ro"
        networks:
            - devops-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - devops-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    devops-network:

